//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVT.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LVT.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    ViewData[&quot;Title&quot;] = &quot;LVT Visualisation&quot;;
        ///}
        ///
        ///&lt;div&gt;
        ///
        ///    &lt;h2&gt;Create your LVT from JSON data&lt;/h2&gt;
        ///    &lt;form method=&quot;post&quot; enctype=&quot;multipart/form-data&quot; asp-controller=&quot;UploadFiles&quot; asp-action=&quot;Index&quot;&gt;
        ///        &lt;div class=&quot;form-group&quot;&gt;
        ///            &lt;div class=&quot;col-md-10&quot;&gt;
        ///                &lt;p&gt;Select the JSON file you want to visualise:&lt;/p&gt;
        ///                &lt;input type=&quot;file&quot; name=&quot;file&quot; /&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;form-group&quot;&gt;
        ///            &lt;div class=&quot;col-md-10&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testhtml {
            get {
                return ResourceManager.GetString("testhtml", resourceCulture);
            }
        }
    }
}
