//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LVT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SingleBranchLVT {
            get {
                object obj = ResourceManager.GetObject("SingleBranchLVT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    ViewData[&quot;Title&quot;] = &quot;Your LVT&quot;;
        ///}
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;LVT Visualisation&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;https://www.gstatic.com/charts/loader.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        google.charts.load(&apos;current&apos;, { packages: [&quot;orgchart&quot;] });
        ///        google.charts.setOnLoadCallback(drawChart);
        ///
        ///        function drawChart() {
        ///            var data = new google.visualization.Data [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateCSHTMLPageTop {
            get {
                return ResourceManager.GetString("TemplateCSHTMLPageTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to );
        ///
        ///            // Create the chart using Google Charts.
        ///            var chart = new google.visualization.OrgChart(document.getElementById(&apos;chart_div&apos;));
        ///            // Draw the chart, setting the allowHtml option to true for the tooltips.
        ///            chart.draw(data, { allowHtml: true });
        ///        }
        ///    &lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;chart_div&quot;&gt;&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string TemplateHTMLPageBottom {
            get {
                return ResourceManager.GetString("TemplateHTMLPageBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;LVT Visualisation&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;https://www.gstatic.com/charts/loader.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        google.charts.load(&apos;current&apos;, { packages: [&quot;orgchart&quot;] });
        ///        google.charts.setOnLoadCallback(drawChart);
        ///
        ///        function drawChart() {
        ///            var data = new google.visualization.DataTable();
        ///            dat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateHTMLPageTop {
            get {
                return ResourceManager.GetString("TemplateHTMLPageTop", resourceCulture);
            }
        }
    }
}
